# Generated by Django 2.2.3 on 2019-08-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20190820_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
        migrations.DeleteModel(
            name='CategoryItem',
        ),
    ]
